name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: docker build -t eyecon:latest .

    - name: Run Docker container
      run: |
        docker run --name eyecon -d eyecon:latest
        sleep 10
      continue-on-error: true

    - name: Check if container is running
      run: |
        if [ $(docker ps -q -f name=eyecon) ]; then
          echo "Container is running."
        else
          echo "Container failed to run."
          docker logs eyecon
          exit 1
        fi

    - name: Clean up
      if: always()
      run: |
        docker stop eyecon || true
        docker rm eyecon || true
        docker rmi eyecon:latest || true
